In [1]:
import numpy as np
a = np.ones((3,2))
b = np.array([7,8])
a = np.append(a,[b], axis = 0)
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [7., 8.]])

In [2]:
a = np.ones((2,3))
b = np.array([7,8,8])
a = np.vstack((a,b))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [7., 8., 8.]])

In [6]:
# create 8x8 array with random integers in the interval [0, 10)
r = np.random.randint(0, 10, (8,8))
# display color map of array using seaborn
import seaborn as sns
sns.heatmap(r)

ModuleNotFoundError: No module named 'seaborn'

In [7]:
a = np.ones((3,2))
b = np.array([[7],[8],[9]])
print(b)
a = np.hstack((a,b))
#c = np.ones((3,1))
#a = np.hstack((a,c))
a

[[7]
 [8]
 [9]]


array([[1., 1., 7.],
       [1., 1., 8.],
       [1., 1., 9.]])

In [13]:
# selecting rows that meet a condition
import pandas as pd
X = np.array([1,2,3])
Y = np.array([4,5,6])
data = np.vstack((X,Y))  # vertical stack
df = pd.DataFrame(data.T, columns=['X','Y'])
df.head()
new_df = df[df['X']<3]
new_df
# add a new column to the dataframe


X  Y
0  1  4
1  2  5

In [ ]:
# making blobs with sklearn
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()  # for plot styling
import numpy as np
from sklearn.datasets import make_blobs
X, y_true = make_blobs(n_samples=300, centers=2,
                       cluster_std=0.60, random_state=0)
plt.scatter(X[:, 0], X[:, 1], s=50);